### ISSUE TITLE
LoadingView.swift: Use of unimplemented initializer init(layer:)

### ISSUE THREAD

**Issue by tuanhoang90896** [livechat/chat-window-ios#65]
After install SmartLook library(https://smartlook.github.io/docs/sdk/ios/), when i open LiveChat app crash. Before LiveChat work normal.
Can you help me!

![Screenshot at Jul 07 10-28-20](https://user-images.githubusercontent.com/31724821/87106680-2debf280-c288-11ea-85c6-6a2d54bd7926.png)

**Comment by kamil-szostakowski** [comment]
@tuanhoang90896 of course we will take a look at your issue. Could you please attach a simple demo project reproducing a problem?

**Comment by imegoff** [comment]
@tuanhoang90896 we investigated the issue. The solution we tried to introduce caused some additional, more extended problems. We decided to leave it unresolved as we are developing new LiveChat mobile apps (LiveChat Lite, you can find them in iOS and Android stores).

**Comment by kamil-szostakowski** [comment]
@tuanhoang90896 the crash is fixed in version `2.0.20` however we recommend pausing smart look recording during interaction with the widget as we don't officially support this library in our widget. Recording can be paused using `Smartlook.stopRecording()` as stated in smart look [documentation](https://smartlook.github.io/docs/sdk/ios/).

**Comment by tuanhoang90896** [comment]
@kamil-szostakowski it work for me. thank you verry much
