### ISSUE TITLE
Github 

### ISSUE THREAD

**Issue by rafiq34** [livechat/chat-window-ios#7]
Please help how can got code

**Comment by msypko** [comment]
Hi @rafiq34!

Could you elaborate what your issue is? What code do you mean?

I recommend you to visit our chat on www.livechatinc.com and elaborate your question to get help immediately. Our Support Heroes would be happy to help you :-) Our operators are available 24/7/365.

You can always shoot us an email too: support@livechatinc.com

**Comment by kamil-szostakowski** [comment]
Closed due to inactivity.
