### ISSUE TITLE
this error 

### ISSUE THREAD

**Issue by 903669695** [livechat/chat-window-ios#77]
![IMG_1992](https://user-images.githubusercontent.com/10215733/108397659-2693bb00-7253-11eb-9989-b55b6634d777.PNG)

**Comment by ZiggyKraus** [comment]
Hello @903669695  !

Krzysztof here, from LiveChat's Technical Support. First of all, our apologies for the late reply.

We have investigated this problem, and it seems that it is most likely caused by the custom configuration of the network to which your device connects (it may also be caused by a VPN/proxy software that you may use to route the connection). It's hard to pinpoint the exact cause at our side, but it looks like the software/network configuration may replace the security certificate on the fly, thus causing the issue with our application. Because of that, we'd like to suggest checking the points mentioned above.

The error itself can be a consequence of misconfiguration of the certificate on the server (in this case secure.livechatinc.com), but to be sure, we have checked the certificates used on our servers, and everything seems to be in order. We have also tracked our customers' recent reports, and there's nothing that would indicate a possible problem for a specific region.

@903669695  I hope that this will help! I wish that we could do more here, but many factors can trigger such behaviour in case of network errors, and it is hard to pinpoint the exact one that is causing the issue.
