### ISSUE TITLE
.mm file  @import LiveChat an error Use of '@import' when C++ modules are disabled, consider using -fmodules and -fcxx-modules

### ISSUE THREAD

**Issue by wwj256** [livechat/chat-window-ios#83]
![QQ20210617-154733](https://user-images.githubusercontent.com/190939/122360694-2c8f7380-cf89-11eb-85a1-9c536dd9ea47.png)
![QQ20210617-163159](https://user-images.githubusercontent.com/190939/122361211-9f005380-cf89-11eb-8165-c4c251542d56.png)

pod 'LiveChat', '~> 2.0.20'
My project will use.mm file, @import LiveChat error
There is no way to use #import
Thank you very mush!

**Comment by wwj256** [comment]
use Xcode version 12.3(12C33)

**Comment by wwj256** [comment]
I created a.m file, added a public method, and then.mm to call it, that is, my project is horizontal, LiveChat will not become vertical after opening, what is the solution?
`+(void)showChat:(NSString*)name email:(NSString*)email
{
    LiveChat.licenseId = @"1283333"; // Set your licence number here
    //LiveChat.groupId = @"1"; // Optionally, you can set specific group
    LiveChat.name = name; // User name and email can be provided if known
    LiveChat.email = email;
    
    [LiveChat presentChatWithAnimated:YES completion:nil];
}`

**Comment by kamil-szostakowski** [comment]
Hello @wwj256. Unfortunately, your issue is not reproducible on our end. Could you please provide a sample project reproducing this issue?

**I did the following steps.**
1. Created ObjC project.
2. Integrated the widget as SPM.
3. Added .mm file. (with some actual C++ code)
4. Reference class defined in .mm file in AppDelegate.

App build without any issues and the widget was displayed without any issues.

**Comment by kamil-szostakowski** [comment]
Closed due to inactivity.
